# MLB Pitching Data Exploration

This notebook pulls Statcast pitching data with pybaseball, explores pitch-level columns, and creates a pitcher strikeout summary by game.

In [227]:
import pandas as pd
import numpy as np

from pybaseball import pitching_stats

In [228]:
import pybaseball
dir(pybaseball)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'all_star_full',
 'all_star_game_logs',
 'amateur_draft',
 'amateur_draft_by_team',
 'appearances',
 'awards_managers',
 'awards_players',
 'awards_share_managers',
 'awards_share_players',
 'batting',
 'batting_leaders',
 'batting_post',
 'batting_stats',
 'batting_stats_bref',
 'batting_stats_range',
 'bwar_bat',
 'bwar_pitch',
 'cache',
 'chadwick_register',
 'college_playing',
 'datahelpers',
 'datasources',
 'division_series_logs',
 'download_lahman',
 'enums',
 'events',
 'fangraphs_teams',
 'fg_batting_data',
 'fg_pitching_data',
 'fg_team_batting_data',
 'fg_team_fielding_data',
 'fg_team_pitching_data',
 'fielding',
 'fielding_leaders',
 'fielding_of',
 'fielding_of_split',
 'fielding_post',
 'fielding_stats',
 'get_splits',
 'hall_of_fame',
 'home_games',
 'lahman',
 'lcs_logs',
 'league_batting_stats',
 'league_pitching_stats',
 'managers',
 'managers_half',
 'master',
 'park_codes',
 'parks',
 'people',
 'pitching',
 'pitching_leaders',
 'pitching_post',
 'pitching_stats',
 'pitching_stats_bref',
 'pitching_stats_range',
 'player_search_list',
 'playerid_lookup',
 'playerid_reverse_lookup',
 'plot_stadium',
 'plot_strike_zone',
 'plot_teams',
 'plotting',
 'pybaseball',
 'retrosheet',
 'rosters',
 'salaries',
 'schedule_and_record',
 'schedules',
 'schools',
 'season_game_logs',
 'series_post',
 'split_stats',
 'spraychart',
 'standings',
 'statcast',
 'statcast_batter',
 'statcast_batter_exitvelo_barrels',
 'statcast_batter_expected_stats',
 'statcast_batter_percentile_ranks',
 'statcast_batter_pitch_arsenal',
 'statcast_catcher_framing',
 'statcast_catcher_poptime',
 'statcast_fielding',
 'statcast_outfield_catch_prob',
 'statcast_outfield_directional_oaa',
 'statcast_outfielder_jump',
 'statcast_outs_above_average',
 'statcast_pitcher',
 'statcast_pitcher_arsenal_stats',
 'statcast_pitcher_exitvelo_barrels',
 'statcast_pitcher_expected_stats',
 'statcast_pitcher_percentile_ranks',
 'statcast_pitcher_pitch_arsenal',
 'statcast_pitcher_spin_dir_comp',
 'statcast_running',
 'statcast_running_splits',
 'statcast_single_game',
 'statcast_sprint_speed',
 'team_batting',
 'team_batting_bref',
 'team_fielding',
 'team_fielding_bref',
 'team_game_logs',
 'team_ids',
 'team_pitching',
 'team_pitching_bref',
 'team_results',
 'teamid_lookup',
 'teams_core',
 'teams_franchises',
 'teams_half',
 'teams_upstream',
 'top_prospects',
 'utils',
 'version',
 'wild_card_logs',
 'world_series_logs']

In [229]:
from pybaseball import playerid_lookup, statcast_pitcher

In [230]:
playerid_lookup('skubal', 'tarik')

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,skubal,tarik,669373,skubt001,skubata01,22267,2020.0,2026.0

In [231]:
skubal = statcast_pitcher('2025-03-01', '2025-10-01', 669373)
skubal.head()

Gathering Player Data

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,SI,2025-09-30,97.6,1.61,6.24,"Skubal, Tarik",680757,669373,field_out,hit_into_play,...,1.0,1.21,1.22,1.22,53.3,-4.898482,9.285544,32.786069,32.569959,20.44196
1,SI,2025-09-30,98.3,1.60,6.12,"Skubal, Tarik",680757,669373,NaN,ball,...,1.0,1.27,1.31,1.31,48.8,NaN,NaN,NaN,NaN,NaN
2,CH,2025-09-30,88.9,1.81,6.05,"Skubal, Tarik",595978,669373,walk,blocked_ball,...,NaN,2.87,1.64,-1.64,42.6,NaN,NaN,NaN,NaN,NaN
3,SL,2025-09-30,89.5,2.02,6.02,"Skubal, Tarik",595978,669373,NaN,called_strike,...,NaN,2.44,-0.27,0.27,45.8,NaN,NaN,NaN,NaN,NaN
4,FF,2025-09-30,96.8,1.55,6.24,"Skubal, Tarik",595978,669373,NaN,called_strike,...,NaN,1.01,0.48,-0.48,52.3,NaN,NaN,NaN,NaN,NaN

In [232]:
skubal.shape

(3208, 119)

In [233]:
skubal.columns

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description',
       ...
       'batter_days_until_next_game', 'api_break_z_with_gravity',
       'api_break_x_arm', 'api_break_x_batter_in', 'arm_angle', 'attack_angle',
       'attack_direction', 'swing_path_tilt',
       'intercept_ball_minus_batter_pos_x_inches',
       'intercept_ball_minus_batter_pos_y_inches'],
      dtype='str', length=119)

In [234]:
skubal.to_csv('../data/skubal_statcast_2025.csv', index=False)

In [235]:
import os
os.listdir('../data')

['daily_pitcher_board_2025-07-12.csv',
 'full_name_pitcher_board_2025.csv',
 'sample_pitcher_board_with_sample_size_2025.csv',
 'skubal_strikeouts_by_game_2025.csv',
 'daily_pitcher_board_2026-06-16.csv',
 'sample_pitcher_board_with_edges_2025.csv',
 'sample_pitcher_board_2025.csv',
 'full_sample_pitcher_board_2025.csv',
 'daily_pitcher_board_2025.csv',
 'skubal_game_logs_2025.csv',
 'pitcher_board_2025.csv',
 'skubal_statcast_2025.csv',
 'sample_pitcher_board_with_status_2025.csv',
 'sample_pitcher_board_with_final_actions_2025.csv',
 'season_flexible_pitcher_board_2025.csv']

In [236]:
skubal[['game_date', 'player_name', 'pitch_type', 'release_speed', 'description', 'events']].head(20)

,game_date,player_name,pitch_type,release_speed,description,events
0,2025-09-30,"Skubal, Tarik",SI,97.6,hit_into_play,field_out
1,2025-09-30,"Skubal, Tarik",SI,98.3,ball,NaN
2,2025-09-30,"Skubal, Tarik",CH,88.9,blocked_ball,walk
3,2025-09-30,"Skubal, Tarik",SL,89.5,called_strike,NaN
4,2025-09-30,"Skubal, Tarik",FF,96.8,called_strike,NaN
5,2025-09-30,"Skubal, Tarik",FF,98.0,ball,NaN
6,2025-09-30,"Skubal, Tarik",SL,89.4,ball,NaN
7,2025-09-30,"Skubal, Tarik",CH,88.3,ball,NaN
8,2025-09-30,"Skubal, Tarik",CH,91.5,swinging_strike_blocked,strikeout
9,2025-09-30,"Skubal, Tarik",CH,88.3,swinging_strike,NaN
10,2025-09-30,"Skubal, Tarik",SL,92.5,foul,NaN
11,2025-09-30,"Skubal, Tarik",SI,101.2,swinging_strike,strikeout
12,2025-09-30,"Skubal, Tarik",FF,96.9,foul,NaN
13,2025-09-30,"Skubal, Tarik",SL,89.9,called_strike,NaN
14,2025-09-30,"Skubal, Tarik",SL,92.5,ball,NaN
15,2025-09-30,"Skubal, Tarik",FF,100.4,swinging_strike,strikeout
16,2025-09-30,"Skubal, Tarik",SL,90.3,swinging_strike,NaN
17,2025-09-30,"Skubal, Tarik",SI,100.4,ball,NaN
18,2025-09-30,"Skubal, Tarik",CH,89.6,swinging_strike,NaN
19,2025-09-30,"Skubal, Tarik",SI,99.7,swinging_strike,strikeout

In [237]:
skubal['pitch_type'].value_counts()

pitch_type
CH    953
FF    922
SI    740
SL    416
CU     90
FS      3
Name: count, dtype: int64

In [238]:
skubal['events'].value_counts().head(20)

events
field_out                    334
strikeout                    278
single                       109
walk                          37
double                        27
home_run                      20
grounded_into_double_play     12
force_out                     12
hit_by_pitch                   5
sac_fly                        3
sac_bunt                       2
triple                         2
field_error                    2
truncated_pa                   2
Name: count, dtype: int64

In [239]:
skubal['events'].value_counts()

events
field_out                    334
strikeout                    278
single                       109
walk                          37
double                        27
home_run                      20
grounded_into_double_play     12
force_out                     12
hit_by_pitch                   5
sac_fly                        3
sac_bunt                       2
triple                         2
field_error                    2
truncated_pa                   2
Name: count, dtype: int64

In [240]:
skubal[skubal['events'] == 'strikeout'].shape

(278, 119)

In [241]:
skubal_strikeouts = skubal[skubal['events'] == 'strikeout']

In [242]:
strikeouts_by_game = skubal_strikeouts.groupby('game_date').size().reset_index(name='strikeouts')

strikeouts_by_game.head()

    game_date  strikeouts
0  2025-03-03           3
1  2025-03-09           4
2  2025-03-15           7
3  2025-03-21           9
4  2025-03-27           2

In [243]:
%whos

Variable                     Type         Data/Info
---------------------------------------------------
add_status                   function     <function add_status at 0x1538931a0>
all_summaries                list         n=2
build_pitcher_board          function     <function build_pitcher_board at 0x153893d80>
compare_to_line              function     <function compare_to_line at 0x153890f40>
daily_lines                  list         n=2
daily_pitcher_board          DataFrame    Shape: (2, 17)
difference                   float64      1.35
final_action                 function     <function final_action at 0x153891300>
label_edge                   function     <function label_edge at 0x153892840>
latest_projection            Series       Shape: (3,)
np                           module       <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
os                           module       <module 'os' from '/usr/l<...>12/lib/python3.12/os.py'>
pd                           module       <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pitcher                      dict         n=3
pitcher_board                DataFrame    Shape: (3, 11)
pitchers_to_test             list         n=3
pitching_stats               method       <bound method FangraphsPi<...>e object at 0x10dbdef90>>
playerid_lookup              function     <function playerid_lookup at 0x10da9f740>
project_pitcher_k            function     <function project_pitcher_k at 0x153892fc0>
projected_k                  float64      8.85
pybaseball                   module       <module 'pybaseball' from<...>/pybaseball/__init__.py'>
recommendation               str          Over
regular_season_start         str          2026-03-25
regular_season_start_dates   dict         n=2
result                       dict         n=6
season                       int          2026
skubal                       DataFrame    Shape: (3208, 119)
skubal_games                 DataFrame    Shape: (32, 7)
skubal_regular               DataFrame    Shape: (2956, 119)
skubal_strikeouts            DataFrame    Shape: (278, 119)
slate_date                   str          2026-06-16
split_pitcher_name           function     <function split_pitcher_name at 0x153893e20>
sportsbook_line              float        7.5
statcast_pitcher             function     <function statcast_pitcher at 0x10dc96e80>
strikeouts_by_game           DataFrame    Shape: (36, 2)
summary                      DataFrame    Shape: (1, 7)

In [244]:
strikeouts_by_game.to_csv('../data/skubal_strikeouts_by_game_2025.csv', index=False)
import os
os.listdir('../data')

['daily_pitcher_board_2025-07-12.csv',
 'full_name_pitcher_board_2025.csv',
 'sample_pitcher_board_with_sample_size_2025.csv',
 'skubal_strikeouts_by_game_2025.csv',
 'daily_pitcher_board_2026-06-16.csv',
 'sample_pitcher_board_with_edges_2025.csv',
 'sample_pitcher_board_2025.csv',
 'full_sample_pitcher_board_2025.csv',
 'daily_pitcher_board_2025.csv',
 'skubal_game_logs_2025.csv',
 'pitcher_board_2025.csv',
 'skubal_statcast_2025.csv',
 'sample_pitcher_board_with_status_2025.csv',
 'sample_pitcher_board_with_final_actions_2025.csv',
 'season_flexible_pitcher_board_2025.csv']

In [245]:
skubal_regular = skubal[skubal['game_date'] >= '2025-03-27'].copy()

In [246]:
skubal_games = (
    skubal_regular.groupby('game_date')
    .agg(
        strikeouts=('events', lambda x: (x == 'strikeout').sum()),
        pitches=('pitch_type', 'count'),
        avg_velocity=('release_speed', 'mean')
    )
    .reset_index()
) 
skubal_games.head()

    game_date  strikeouts  pitches  avg_velocity
0  2025-03-27           2       80     93.151250
1  2025-04-02           8       93     92.670968
2  2025-04-08           6       87     92.851724
3  2025-04-14           9       91     92.924176
4  2025-04-20           4       91     92.569231

In [247]:
skubal_games = skubal_games.sort_values('game_date')
skubal_games

     game_date  strikeouts  pitches  avg_velocity
0   2025-03-27           2       80     93.151250
1   2025-04-02           8       93     92.670968
2   2025-04-08           6       87     92.851724
3   2025-04-14           9       91     92.924176
4   2025-04-20           4       91     92.569231
5   2025-04-27          11       91     93.012088
6   2025-05-02           8       73     94.252055
7   2025-05-09          12       96     94.185417
8   2025-05-14          11       95     94.136842
9   2025-05-20           8       94     93.759574
10  2025-05-25          13       94     94.172340
11  2025-05-31           7       90     93.601111
12  2025-06-06           6       94     94.304255
13  2025-06-12           6       98     92.991837
14  2025-06-19           6      103     92.142718
15  2025-06-24           8       97     92.003093
16  2025-06-29          13       93     92.223656
17  2025-07-06          10       93     92.466667
18  2025-07-11           5       87     92.048276
19  2025-07-20          11      105     91.904762
20  2025-07-26           7       96     92.652083
21  2025-08-02          10       98     93.282653
22  2025-08-08           6       92     93.633696
23  2025-08-14           3       99     92.822222
24  2025-08-19          10       95     92.891579
25  2025-08-25          12       99     93.160606
26  2025-08-31           4       93     92.692473
27  2025-09-06           6       90     94.082222
28  2025-09-12           2       45     91.191111
29  2025-09-18           9      102     93.954902
30  2025-09-23           8       95     93.629474
31  2025-09-30          14      107     94.571963

In [248]:
skubal_games['last_3_avg_k'] = skubal_games['strikeouts'].rolling(3).mean()
skubal_games['last_5_avg_k'] = skubal_games['strikeouts'].rolling(5).mean()
skubal_games['season_avg_k'] = skubal_games['strikeouts'].expanding().mean()

skubal_games

,game_date,strikeouts,pitches,avg_velocity,last_3_avg_k,last_5_avg_k,season_avg_k
0,2025-03-27,2,80,93.151250,NaN,NaN,2.000000
1,2025-04-02,8,93,92.670968,NaN,NaN,5.000000
2,2025-04-08,6,87,92.851724,5.333333,NaN,5.333333
3,2025-04-14,9,91,92.924176,7.666667,NaN,6.250000
4,2025-04-20,4,91,92.569231,6.333333,5.8,5.800000
5,2025-04-27,11,91,93.012088,8.000000,7.6,6.666667
6,2025-05-02,8,73,94.252055,7.666667,7.6,6.857143
7,2025-05-09,12,96,94.185417,10.333333,8.8,7.500000
8,2025-05-14,11,95,94.136842,10.333333,9.2,7.888889
9,2025-05-20,8,94,93.759574,10.333333,10.0,7.900000
10,2025-05-25,13,94,94.172340,10.666667,10.4,8.363636
11,2025-05-31,7,90,93.601111,9.333333,10.2,8.250000
12,2025-06-06,6,94,94.304255,8.666667,9.0,8.076923
13,2025-06-12,6,98,92.991837,6.333333,8.0,7.928571
14,2025-06-19,6,103,92.142718,6.000000,7.6,7.800000
15,2025-06-24,8,97,92.003093,6.666667,6.6,7.812500
16,2025-06-29,13,93,92.223656,9.000000,7.8,8.117647
17,2025-07-06,10,93,92.466667,10.333333,8.6,8.222222
18,2025-07-11,5,87,92.048276,9.333333,8.4,8.052632
19,2025-07-20,11,105,91.904762,8.666667,9.4,8.200000
20,2025-07-26,7,96,92.652083,7.666667,9.2,8.142857
21,2025-08-02,10,98,93.282653,9.333333,8.6,8.227273
22,2025-08-08,6,92,93.633696,7.666667,7.8,8.130435
23,2025-08-14,3,99,92.822222,6.333333,7.4,7.916667
24,2025-08-19,10,95,92.891579,6.333333,7.2,8.000000
25,2025-08-25,12,99,93.160606,8.333333,8.2,8.153846
26,2025-08-31,4,93,92.692473,8.666667,7.0,8.000000
27,2025-09-06,6,90,94.082222,7.333333,7.0,7.928571
28,2025-09-12,2,45,91.191111,4.000000,6.8,7.724138
29,2025-09-18,9,102,93.954902,5.666667,6.6,7.766667
30,2025-09-23,8,95,93.629474,6.333333,5.8,7.774194
31,2025-09-30,14,107,94.571963,10.333333,7.8,7.968750

In [249]:
latest_projection = skubal_games.iloc[-1][['last_3_avg_k', 'last_5_avg_k', 'season_avg_k']]
latest_projection

last_3_avg_k    10.333333
last_5_avg_k          7.8
season_avg_k      7.96875
Name: 31, dtype: object

In [250]:
projected_k = (
    skubal_games.iloc[-1]['last_3_avg_k'] * 0.4 +
    skubal_games.iloc[-1]['last_5_avg_k'] * 0.4 +
    skubal_games.iloc[-1]['season_avg_k'] * 0.2
)

projected_k

np.float64(8.847083333333334)

In [251]:
skubal_games.to_csv('../data/skubal_game_logs_2025.csv', index=False)

## Build a Reusable Pitcher Projection Function

So far, the notebook only worked for one pitcher because the data was stored in variables like `skubal`.

This next section creates a reusable function that can:
- look up a pitcher by name
- pull that pitcher's Statcast data
- remove spring training games
- calculate strikeouts by game
- calculate recent strikeout averages
- create a simple projected strikeout number

In [252]:
from pybaseball import playerid_lookup, statcast_pitcher

def project_pitcher_k(last_name, first_name, season):
    player_ids = playerid_lookup(last_name, first_name)
    mlbam_id = int(player_ids.iloc[0]['key_mlbam'])

    start_date = f'{season}-03-27'
    end_date = f'{season}-10-01'

    data = statcast_pitcher(start_date, end_date, mlbam_id)

    games = (
        data.groupby('game_date')
        .agg(
            strikeouts=('events', lambda x: (x == 'strikeout').sum()),
            pitches=('pitch_type', 'count'),
            avg_velocity=('release_speed', 'mean')
        )
        .reset_index()
        .sort_values('game_date')
    )

    games['last_3_avg_k'] = games['strikeouts'].rolling(3).mean()
    games['last_5_avg_k'] = games['strikeouts'].rolling(5).mean()
    games['season_avg_k'] = games['strikeouts'].expanding().mean()

    latest = games.iloc[-1]

    projected_k = (
        latest['last_3_avg_k'] * 0.4 +
        latest['last_5_avg_k'] * 0.4 +
        latest['season_avg_k'] * 0.2
    )

    return {
        'pitcher': f'{first_name.title()} {last_name.title()}',
        'mlbam_id': mlbam_id,
        'season': season,
        'projected_k': projected_k,
        'games': games
    }

## Test the Projection Function

Now we test the function using Tarik Skubal.

If the function works, it should return:

- the pitcher's name
- the player's MLBAM ID
- the projected strikeout number
- a game-by-game table used to calculate the projection

In [253]:
result = project_pitcher_k('skubal', 'tarik', 2025)

result['pitcher'], result['mlbam_id'], result['projected_k'], result['games']

Gathering Player Data

('Tarik Skubal',
 669373,
 np.float64(8.847083333333334),
      game_date  strikeouts  pitches  avg_velocity  last_3_avg_k  last_5_avg_k  \
 0   2025-03-27           2       80     93.151250           NaN           NaN
 1   2025-04-02           8       93     92.670968           NaN           NaN
 2   2025-04-08           6       87     92.851724      5.333333           NaN
 3   2025-04-14           9       91     92.924176      7.666667           NaN
 4   2025-04-20           4       91     92.569231      6.333333           5.8
 5   2025-04-27          11       91     93.012088      8.000000           7.6
 6   2025-05-02           8       73     94.252055      7.666667           7.6
 7   2025-05-09          12       96     94.185417     10.333333           8.8
 8   2025-05-14          11       95     94.136842     10.333333           9.2
 9   2025-05-20           8       94     93.759574     10.333333          10.0
 10  2025-05-25          13       94     94.172340     10.666667          10.4
 11  2025-05-31           7       90     93.601111      9.333333          10.2
 12  2025-06-06           6       94     94.304255      8.666667           9.0
 13  2025-06-12           6       98     92.991837      6.333333           8.0
 14  2025-06-19           6      103     92.142718      6.000000           7.6
 15  2025-06-24           8       97     92.003093      6.666667           6.6
 16  2025-06-29          13       93     92.223656      9.000000           7.8
 17  2025-07-06          10       93     92.466667     10.333333           8.6
 18  2025-07-11           5       87     92.048276      9.333333           8.4
 19  2025-07-20          11      105     91.904762      8.666667           9.4
 20  2025-07-26           7       96     92.652083      7.666667           9.2
 21  2025-08-02          10       98     93.282653      9.333333           8.6
 22  2025-08-08           6       92     93.633696      7.666667           7.8
 23  2025-08-14           3       99     92.822222      6.333333           7.4
 24  2025-08-19          10       95     92.891579      6.333333           7.2
 25  2025-08-25          12       99     93.160606      8.333333           8.2
 26  2025-08-31           4       93     92.692473      8.666667           7.0
 27  2025-09-06           6       90     94.082222      7.333333           7.0
 28  2025-09-12           2       45     91.191111      4.000000           6.8
 29  2025-09-18           9      102     93.954902      5.666667           6.6
 30  2025-09-23           8       95     93.629474      6.333333           5.8
 31  2025-09-30          14      107     94.571963     10.333333           7.8

     season_avg_k
 0       2.000000
 1       5.000000
 2       5.333333
 3       6.250000
 4       5.800000
 5       6.666667
 6       6.857143
 7       7.500000
 8       7.888889
 9       7.900000
 10      8.363636
 11      8.250000
 12      8.076923
 13      7.928571
 14      7.800000
 15      7.812500
 16      8.117647
 17      8.222222
 18      8.052632
 19      8.200000
 20      8.142857
 21      8.227273
 22      8.130435
 23      7.916667
 24      8.000000
 25      8.153846
 26      8.000000
 27      7.928571
 28      7.724138
 29      7.766667
 30      7.774194
 31      7.968750  )

## Compare Projection to a Sportsbook Line

Now that we have our own projected strikeout number, we can compare it to a sportsbook line.

For example, if our model projects 8.84 strikeouts and the sportsbook line is 7.5, then our projection is higher than the line.

That would lean toward the over.

If our projection is lower than the sportsbook line, that would lean toward the under.

In [254]:
sportsbook_line = 7.50
projected_k = round(result['projected_k'], 2)

difference = round(projected_k - sportsbook_line, 2)

projected_k, sportsbook_line, difference

(np.float64(8.85), 7.5, np.float64(1.35))

## Create a Simple Betting Lean

This step turns the projection difference into a simple recommendation.

For now, the logic is:

- If our projection is at least 0.5 strikeouts above the line, lean Over
- If our projection is at least 0.5 strikeouts below the line, lean Under
- If the difference is smaller than 0.5, call it No Bet

This keeps us from forcing a bet when the projection and sportsbook line are too close.

In [255]:
if difference >= 0.5:
    recommendation = 'Over'
elif difference <= -0.5:
    recommendation = 'Under'
else:
    recommendation = 'No Bet'

recommendation

'Over'

## Build a Clean Projection Summary

This creates a simple summary table showing the pitcher, projection, sportsbook line, difference, and recommendation.

This is the first version of the final output we eventually want for every pitcher on a given day.

In [256]:
summary = pd.DataFrame([{
    'pitcher': result['pitcher'],
    'projected_k': round(projected_k, 2),
    'sportsbook_line': sportsbook_line,
    'difference': round(difference, 2),
    'recommendation': recommendation
}])

summary

        pitcher  projected_k  sportsbook_line  difference recommendation
0  Tarik Skubal         8.85              7.5        1.35           Over

## Create a Reusable Sportsbook Comparison Function

Now we turn the sportsbook comparison into a reusable function.

This function takes:

- a pitcher projection result
- a sportsbook strikeout line

It returns a clean summary table with:

- pitcher name
- projected strikeouts
- sportsbook line
- difference
- recommendation

All displayed numbers are rounded to hundredths.

In [257]:
def compare_to_line(result, sportsbook_line):
    projected_k = round(result['projected_k'], 2)
    difference = round(projected_k - sportsbook_line, 2)

    if difference >= 0.5:
        recommendation = 'Over'
    elif difference <= -0.5:
        recommendation = 'Under'
    else:
        recommendation = 'No Bet'

    summary = pd.DataFrame([{
        'pitcher': result['pitcher'],
        'projected_k': projected_k,
        'sportsbook_line': sportsbook_line,
        'difference': difference,
        'recommendation': recommendation
    }])

    return summary

## Test the Sportsbook Comparison Function

Now we test the comparison function using Tarik Skubal and a sample sportsbook line of 7.5 strikeouts.

This should return a one-row summary table with the projected strikeouts, the sportsbook line, and the recommendation.

In [258]:
compare_to_line(result, 7.5)

        pitcher  projected_k  sportsbook_line  difference recommendation
0  Tarik Skubal         8.85              7.5        1.35           Over

## Project Multiple Pitchers

So far, the notebook can project one pitcher at a time.

Now we will test the projection function on multiple pitchers. This helps confirm that the workflow can handle more than one player and gives us the first version of a daily pitcher board.

In [259]:
pitchers_to_test = [
    {'last_name': 'skubal', 'first_name': 'tarik', 'line': 7.5},
    {'last_name': 'cole', 'first_name': 'gerrit', 'line': 6.5},
    {'last_name': 'wheeler', 'first_name': 'zack', 'line': 6.5}
]

## Run Projections for Each Pitcher

This loop runs the projection function for each pitcher, compares the projection to the sportsbook line, and stores each summary table.

If one pitcher fails because of missing data or a lookup issue, the notebook prints the error and continues with the next pitcher.

In [260]:
all_summaries = []

for pitcher in pitchers_to_test:
    try:
        result = project_pitcher_k(
            pitcher['last_name'],
            pitcher['first_name'],
            2025
        )

        summary = compare_to_line(result, pitcher['line'])
        all_summaries.append(summary)

    except Exception as e:
        print(f"Error with {pitcher['first_name']} {pitcher['last_name']}: {e}")

Gathering Player Data
Gathering Player Data
Error with gerrit cole: single positional indexer is out-of-bounds
Gathering Player Data

## Create a Simple Pitcher Board

This combines all pitcher summaries into one table.

This table is the first version of what the final project should produce each day: a list of pitchers, projected strikeouts, sportsbook lines, differences, and recommendations.

In [261]:
pitcher_board = pd.concat(all_summaries, ignore_index=True)

pitcher_board

        pitcher  projected_k  sportsbook_line  difference recommendation
0  Tarik Skubal         8.85              7.5        1.35           Over
1  Zack Wheeler         7.97              6.5        1.47           Over

## Save the Pitcher Board

Finally, we save the pitcher board to a CSV file so we can review it later or use it in another script.

In [262]:
pitcher_board.to_csv('../data/sample_pitcher_board_2025.csv', index=False)

## Add Edge Strength

The difference between our projection and the sportsbook line is called the edge.

A bigger edge means our projection disagrees more strongly with the sportsbook line.

For this first version, we will label each edge like this:

- Strong Edge: difference is 1.5 strikeouts or more
- Medium Edge: difference is 1.0 to 1.49 strikeouts
- Small Edge: difference is 0.5 to 0.99 strikeouts
- No Bet: difference is less than 0.5 strikeouts

In [263]:
def label_edge(difference):
    abs_difference = abs(difference)

    if abs_difference >= 1.5:
        return 'Strong Edge'
    elif abs_difference >= 1.0:
        return 'Medium Edge'
    elif abs_difference >= 0.5:
        return 'Small Edge'
    else:
        return 'No Bet'

## Apply Edge Strength to the Pitcher Board

Now we add the edge strength label to each pitcher.

This makes the board easier to read because we can quickly see which projections are strongest.

In [264]:
pitcher_board['edge_strength'] = pitcher_board['difference'].apply(label_edge)

pitcher_board

,pitcher,projected_k,sportsbook_line,difference,recommendation,edge_strength
0,Tarik Skubal,8.85,7.5,1.35,Over,Medium Edge
1,Zack Wheeler,7.97,6.5,1.47,Over,Medium Edge

## Sort the Pitcher Board

Now we sort the board so the biggest edges appear first.

We use the absolute value of the difference because both Over and Under recommendations can be valuable.

In [265]:
pitcher_board['abs_difference'] = pitcher_board['difference'].abs()

pitcher_board = pitcher_board.sort_values('abs_difference', ascending=False)

pitcher_board

,pitcher,projected_k,sportsbook_line,difference,recommendation,edge_strength,abs_difference
1,Zack Wheeler,7.97,6.5,1.47,Over,Medium Edge,1.47
0,Tarik Skubal,8.85,7.5,1.35,Over,Medium Edge,1.35

## Clean the Final Board

The absolute difference column was only needed for sorting.

Now we remove it so the final board is cleaner.

In [266]:
pitcher_board = pitcher_board.drop(columns=['abs_difference'])

pitcher_board

,pitcher,projected_k,sportsbook_line,difference,recommendation,edge_strength
1,Zack Wheeler,7.97,6.5,1.47,Over,Medium Edge
0,Tarik Skubal,8.85,7.5,1.35,Over,Medium Edge

In [267]:
pitcher_board.to_csv('../data/sample_pitcher_board_with_edges_2025.csv', index=False)

## Add Sample Size Awareness

A projection is more trustworthy when it is based on enough starts.

For this first version, we will count how many games were used for each pitcher projection.

Then we will label the sample size:

- Good Sample: 10 or more starts
- Small Sample: fewer than 10 starts

This helps us avoid trusting projections that are based on too little data.

In [268]:
def project_pitcher_k(last_name, first_name, season):
    player_ids = playerid_lookup(last_name, first_name)
    mlbam_id = int(player_ids.iloc[0]['key_mlbam'])

    start_date = f'{season}-03-27'
    end_date = f'{season}-10-01'

    data = statcast_pitcher(start_date, end_date, mlbam_id)

    games = (
        data.groupby('game_date')
        .agg(
            strikeouts=('events', lambda x: (x == 'strikeout').sum()),
            pitches=('pitch_type', 'count'),
            avg_velocity=('release_speed', 'mean')
        )
        .reset_index()
        .sort_values('game_date')
    )

    games['last_3_avg_k'] = games['strikeouts'].rolling(3).mean()
    games['last_5_avg_k'] = games['strikeouts'].rolling(5).mean()
    games['season_avg_k'] = games['strikeouts'].expanding().mean()

    latest = games.iloc[-1]

    projected_k = (
        latest['last_3_avg_k'] * 0.4 +
        latest['last_5_avg_k'] * 0.4 +
        latest['season_avg_k'] * 0.2
    )

    return {
        'pitcher': f'{first_name.title()} {last_name.title()}',
        'mlbam_id': mlbam_id,
        'season': season,
        'projected_k': projected_k,
        'games_used': len(games),
        'games': games
    }

## Update the Sportsbook Comparison Function

Now we update the sportsbook comparison function so the output includes sample size.

The function will still compare our projected strikeouts to the sportsbook line, but now it will also show how many games were used and whether that is a good or small sample.

In [269]:
def compare_to_line(result, sportsbook_line):
    projected_k = round(result['projected_k'], 2)
    difference = round(projected_k - sportsbook_line, 2)

    if difference >= 0.5:
        recommendation = 'Over'
    elif difference <= -0.5:
        recommendation = 'Under'
    else:
        recommendation = 'No Bet'

    if result['games_used'] >= 10:
        sample_size = 'Good Sample'
    else:
        sample_size = 'Small Sample'

    summary = pd.DataFrame([{
        'pitcher': result['pitcher'],
        'games_used': result['games_used'],
        'projected_k': projected_k,
        'sportsbook_line': sportsbook_line,
        'difference': difference,
        'recommendation': recommendation,
        'sample_size': sample_size
    }])

    return summary

## Rebuild the Pitcher Board With Sample Size

Now we rerun the multiple-pitcher workflow.

This step uses the updated functions, so each pitcher summary will include games used and sample size.

In [270]:
all_summaries = []

for pitcher in pitchers_to_test:
    try:
        result = project_pitcher_k(
            pitcher['last_name'],
            pitcher['first_name'],
            2025
        )

        summary = compare_to_line(result, pitcher['line'])
        all_summaries.append(summary)

    except Exception as e:
        print(f"Error with {pitcher['first_name']} {pitcher['last_name']}: {e}")

Gathering Player Data
Gathering Player Data
Error with gerrit cole: single positional indexer is out-of-bounds
Gathering Player Data

## Combine the Updated Summaries

This combines the individual pitcher summaries into one board.

After this step, the board should include sample size information for each pitcher.

In [271]:
pitcher_board = pd.concat(all_summaries, ignore_index=True)

pitcher_board

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample
1,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample

In [272]:
pitcher_board['edge_strength'] = pitcher_board['difference'].apply(label_edge)

pitcher_board

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge
1,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge

In [273]:
pitcher_board['abs_difference'] = pitcher_board['difference'].abs()

pitcher_board = pitcher_board.sort_values('abs_difference', ascending=False)

pitcher_board = pitcher_board.drop(columns=['abs_difference'])

pitcher_board

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength
1,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge

In [274]:
pitcher_board.to_csv('../data/sample_pitcher_board_with_sample_size_2025.csv', index=False)

## Add Final Bet or Pass Logic

Now we create a final action column.

The recommendation column says whether the projection leans Over, Under, or No Bet.

The final action column is stricter. It only says to bet when:

- the sample size is good
- the edge is at least medium
- the recommendation is Over or Under

Otherwise, the action is Pass.

In [275]:
def final_action(row):
    if (
        row['sample_size'] == 'Good Sample'
        and row['edge_strength'] in ['Medium Edge', 'Strong Edge']
        and row['recommendation'] == 'Over'
    ):
        return 'Bet Over'

    elif (
        row['sample_size'] == 'Good Sample'
        and row['edge_strength'] in ['Medium Edge', 'Strong Edge']
        and row['recommendation'] == 'Under'
    ):
        return 'Bet Under'

    else:
        return 'Pass'

## Apply Final Bet or Pass Logic

Now we apply the final action function to every row in the pitcher board.

This gives us a clearer final decision for each pitcher.

In [276]:
pitcher_board['final_action'] = pitcher_board.apply(final_action, axis=1)

pitcher_board

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action
1,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over

In [277]:
pitcher_board.to_csv('../data/sample_pitcher_board_with_final_actions_2025.csv', index=False)

## Create a Full Pitcher Board Function

Now we combine the projection, sportsbook comparison, edge strength, and final action logic into one reusable function.

This function takes a list of pitchers and lines, then returns a complete pitcher board.

Each pitcher needs:

- first name
- last name
- sportsbook strikeout line

The function will:

1. Project each pitcher's strikeouts
2. Compare the projection to the sportsbook line
3. Add edge strength
4. Add final bet/pass action
5. Return one clean board

In [278]:
def build_pitcher_board(pitchers, season):
    all_summaries = []

    for pitcher in pitchers:
        try:
            result = project_pitcher_k(
                pitcher['last_name'],
                pitcher['first_name'],
                season
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            print(f"Error with {pitcher['first_name']} {pitcher['last_name']}: {e}")

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(label_edge)
    board['final_action'] = board.apply(final_action, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False)
    board = board.drop(columns=['abs_difference'])

    return board

## Test the Full Pitcher Board Function

Now we test the full board function using the sample pitchers and sportsbook lines.

This should return the full board in one step.

In [279]:
pitchers_to_test = [
    {'last_name': 'skubal', 'first_name': 'tarik', 'line': 7.5},
    {'last_name': 'cole', 'first_name': 'gerrit', 'line': 6.5},
    {'last_name': 'wheeler', 'first_name': 'zack', 'line': 6.5}
]

pitcher_board = build_pitcher_board(pitchers_to_test, 2025)

pitcher_board

Gathering Player Data
Gathering Player Data
Error with gerrit cole: single positional indexer is out-of-bounds
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action
1,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over

In [280]:
pitcher_board.to_csv('../data/full_sample_pitcher_board_2025.csv', index=False)

## Handle Pitchers With Missing Data

Some pitchers may not have data for the selected season.

This can happen if the pitcher was injured, did not pitch, changed roles, or if the name lookup does not return usable data.

Instead of skipping those pitchers, we will add them to the board with a clear status of No Data.

In [281]:
def build_pitcher_board(pitchers, season):
    all_summaries = []

    for pitcher in pitchers:
        try:
            result = project_pitcher_k(
                pitcher['last_name'],
                pitcher['first_name'],
                season
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': f"{pitcher['first_name'].title()} {pitcher['last_name'].title()}",
                'games_used': 0,
                'projected_k': None,
                'sportsbook_line': pitcher['line'],
                'difference': None,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    return board

## Fix Sorting When Some Pitchers Have No Data

When a pitcher has no data, the difference value is missing.

To keep the board sortable, missing numeric values should be stored as `np.nan` instead of `None`.

This lets pandas treat the column as numeric and sort missing values last.

In [282]:
def build_pitcher_board(pitchers, season):
    all_summaries = []

    for pitcher in pitchers:
        try:
            result = project_pitcher_k(
                pitcher['last_name'],
                pitcher['first_name'],
                season
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': f"{pitcher['first_name'].title()} {pitcher['last_name'].title()}",
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    return board

In [283]:
pitcher_board = build_pitcher_board(pitchers_to_test, 2025)

pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass

## Add a Status Column

Now we add a status column to make the board easier to interpret.

The status column summarizes each row:

- Playable: the final action is Bet Over or Bet Under
- Pass - Small Edge: the projection is too close to the sportsbook line
- Pass - Small Sample: there are not enough starts
- No Data: the pitcher does not have usable data

In [284]:
def add_status(row):
    if row['recommendation'] == 'No Data':
        return 'No Data'

    if row['final_action'] in ['Bet Over', 'Bet Under']:
        return 'Playable'

    if row['sample_size'] == 'Small Sample':
        return 'Pass - Small Sample'

    if row['edge_strength'] == 'Small Edge' or row['edge_strength'] == 'No Bet':
        return 'Pass - Small Edge'

    return 'Pass'

## Update the Full Board Function With Status

Now we update the full board function so every pitcher gets a status label.

This makes the final board easier to scan.

In [285]:
def build_pitcher_board(pitchers, season):
    all_summaries = []

    for pitcher in pitchers:
        try:
            result = project_pitcher_k(
                pitcher['last_name'],
                pitcher['first_name'],
                season
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': f"{pitcher['first_name'].title()} {pitcher['last_name'].title()}",
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    return board

In [286]:
pitcher_board = build_pitcher_board(pitchers_to_test, 2025)

pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data

In [287]:
pitcher_board.to_csv('../data/sample_pitcher_board_with_status_2025.csv', index=False)

## Make the Projection Function Season Flexible

The current projection function uses a hardcoded regular season start date.

That works for 2025 because the regular season started on March 27, 2025.

To make the project work for future seasons, including 2026, we will update the function so the regular season start date can be entered as an input.

In [288]:
def project_pitcher_k(last_name, first_name, season, regular_season_start):
    player_ids = playerid_lookup(last_name, first_name)
    mlbam_id = int(player_ids.iloc[0]['key_mlbam'])

    start_date = regular_season_start
    end_date = f'{season}-10-01'

    data = statcast_pitcher(start_date, end_date, mlbam_id)

    games = (
        data.groupby('game_date')
        .agg(
            strikeouts=('events', lambda x: (x == 'strikeout').sum()),
            pitches=('pitch_type', 'count'),
            avg_velocity=('release_speed', 'mean')
        )
        .reset_index()
        .sort_values('game_date')
    )

    games['last_3_avg_k'] = games['strikeouts'].rolling(3).mean()
    games['last_5_avg_k'] = games['strikeouts'].rolling(5).mean()
    games['season_avg_k'] = games['strikeouts'].expanding().mean()

    latest = games.iloc[-1]

    projected_k = (
        latest['last_3_avg_k'] * 0.4 +
        latest['last_5_avg_k'] * 0.4 +
        latest['season_avg_k'] * 0.2
    )

    return {
        'pitcher': f'{first_name.title()} {last_name.title()}',
        'mlbam_id': mlbam_id,
        'season': season,
        'regular_season_start': regular_season_start,
        'projected_k': projected_k,
        'games_used': len(games),
        'games': games
    }

## Update the Board Function for Season Start Date

Now we update the full board function so it accepts a regular season start date.

This keeps the board flexible for different seasons.

In [289]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            result = project_pitcher_k(
                pitcher['last_name'],
                pitcher['first_name'],
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': f"{pitcher['first_name'].title()} {pitcher['last_name'].title()}",
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    return board

In [290]:
pitcher_board = build_pitcher_board(
    pitchers_to_test,
    2025,
    '2025-03-27'
)

pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data

In [291]:
pitcher_board.to_csv('../data/season_flexible_pitcher_board_2025.csv', index=False)

## Store Regular Season Start Dates

Each MLB season can start on a different date.

Instead of typing the regular season start date manually every time, we can store known season start dates in a dictionary.

This makes the project easier to reuse across seasons.

In [292]:
regular_season_start_dates = {
    2025: '2025-03-27',
    2026: '2026-03-25'
}

## Build a Board Using the Stored Season Start Date

Now we can choose a season and let Python look up the correct regular season start date.

This reduces manual typing and helps avoid date mistakes.

In [293]:
season = 2025
regular_season_start = regular_season_start_dates[season]

pitcher_board = build_pitcher_board(
    pitchers_to_test,
    season,
    regular_season_start
)

pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data

In [294]:
pitcher_board.to_csv(f'../data/pitcher_board_{season}.csv', index=False)

## Use Full Pitcher Names

The current pitcher input requires separate first and last name fields.

To make the project easier to use, we will allow pitcher names to be entered as full names, such as `Tarik Skubal`.

This is closer to how a user would naturally enter sportsbook lines.

In [295]:
def split_pitcher_name(full_name):
    name_parts = full_name.strip().split()

    first_name = name_parts[0].lower()
    last_name = name_parts[-1].lower()

    return first_name, last_name

## Test the Name Splitting Function

Now we test the helper function with a pitcher name.

The function should return the first name and last name in lowercase.

In [296]:
split_pitcher_name('Tarik Skubal')

('tarik', 'skubal')

## Update the Board Function for Full Names

Now we update the board function so each pitcher can be entered with a single `pitcher` field.

The function will split the full name into first and last name before looking up the player.

In [297]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            first_name, last_name = split_pitcher_name(pitcher['pitcher'])

            result = project_pitcher_k(
                last_name,
                first_name,
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': pitcher['pitcher'],
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    return board

## Create a Full-Name Pitcher Input List

Now the input list is easier to read and easier to edit.

Each row includes the pitcher name and the sportsbook strikeout line.

In [298]:
pitchers_to_test = [
    {'pitcher': 'Tarik Skubal', 'line': 7.5},
    {'pitcher': 'Gerrit Cole', 'line': 6.5},
    {'pitcher': 'Zack Wheeler', 'line': 6.5}
]

In [299]:
season = 2025
regular_season_start = regular_season_start_dates[season]

pitcher_board = build_pitcher_board(
    pitchers_to_test,
    season,
    regular_season_start
)

pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data

In [300]:
pitcher_board.to_csv(f'../data/full_name_pitcher_board_{season}.csv', index=False)

## Create a Manual Daily Lines Table

The first usable version of this project will use manually entered sportsbook lines.

Each day, the user can enter the pitchers they want to evaluate and the sportsbook strikeout line for each pitcher.

Later, this data could come from an API or another data source, but manual entry is a good first version.

In [301]:
daily_lines = [
    {'pitcher': 'Tarik Skubal', 'line': 7.5},
    {'pitcher': 'Gerrit Cole', 'line': 6.5},
    {'pitcher': 'Zack Wheeler', 'line': 6.5}
]

## Build the Daily Pitcher Board

Now we use the manually entered daily lines to build the pitcher board.

The board will project each pitcher, compare the projection to the sportsbook line, and return a final action.

In [302]:
season = 2025
regular_season_start = regular_season_start_dates[season]

daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data

In [303]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{season}.csv', index=False)

## Add a Slate Date

A slate date is the date of the games we are evaluating.

Adding a slate date makes the output easier to track because each saved board can be tied to a specific MLB schedule day.

In [304]:
slate_date = '2025-07-12'

## Build the Daily Board for a Slate Date

Now we build the daily pitcher board using the manually entered lines and the selected slate date.

The slate date will be added to the board as a column.

In [305]:
season = 2025
regular_season_start = regular_season_start_dates[season]

daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,error_message,edge_strength,final_action,status,slate_date
2,Zack Wheeler,24,7.97,6.5,1.47,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,32,8.85,7.5,1.35,Over,Good Sample,NaN,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,0,NaN,6.5,NaN,No Data,No Data,single positional indexer is out-of-bounds,No Data,Pass,No Data,2025-07-12

In [306]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Add Opponent Information

Pitcher strikeout projections depend partly on the opponent.

For now, we will manually enter each pitcher's opponent so the daily board keeps track of the matchup.

Later, opponent strikeout rates can become part of the projection model.

In [307]:
daily_lines = [
    {'pitcher': 'Tarik Skubal', 'opponent': 'CLE', 'line': 7.5},
    {'pitcher': 'Gerrit Cole', 'opponent': 'BOS', 'line': 6.5},
    {'pitcher': 'Zack Wheeler', 'opponent': 'ATL', 'line': 6.5}
]

## Update the Board Function With Opponent

Now we update the board function so the opponent from the daily lines input is included in the final board.

This does not change the projection yet, but it makes the board more useful and prepares the project for matchup adjustments later.

In [308]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            first_name, last_name = split_pitcher_name(pitcher['pitcher'])

            result = project_pitcher_k(
                last_name,
                first_name,
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            summary['opponent'] = pitcher['opponent']

            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': pitcher['pitcher'],
                'opponent': pitcher['opponent'],
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    columns = [
        'pitcher',
        'opponent',
        'games_used',
        'projected_k',
        'sportsbook_line',
        'difference',
        'recommendation',
        'sample_size',
        'edge_strength',
        'final_action',
        'status'
    ]

    return board[columns]

In [309]:
daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,opponent,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
2,Zack Wheeler,ATL,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,CLE,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,BOS,0,NaN,6.5,NaN,No Data,No Data,No Data,Pass,No Data,2025-07-12

In [310]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Add Home or Away Information

Pitcher performance can be different at home compared to on the road.

For now, we will manually enter whether the pitcher is home or away for the slate.

Later, this can be used as a model feature.

In [311]:
daily_lines = [
    {'pitcher': 'Tarik Skubal', 'opponent': 'CLE', 'home_away': 'Home', 'line': 7.5},
    {'pitcher': 'Gerrit Cole', 'opponent': 'BOS', 'home_away': 'Away', 'line': 6.5},
    {'pitcher': 'Zack Wheeler', 'opponent': 'ATL', 'home_away': 'Home', 'line': 6.5}
]

## Update the Board Function With Home or Away

Now we update the board function so home or away information appears in the final pitcher board.

This still does not change the projection, but it gives us another useful context column.

In [312]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            first_name, last_name = split_pitcher_name(pitcher['pitcher'])

            result = project_pitcher_k(
                last_name,
                first_name,
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            summary['opponent'] = pitcher['opponent']
            summary['home_away'] = pitcher['home_away']

            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': pitcher['pitcher'],
                'opponent': pitcher['opponent'],
                'home_away': pitcher['home_away'],
                'games_used': 0,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    columns = [
        'pitcher',
        'opponent',
        'home_away',
        'games_used',
        'projected_k',
        'sportsbook_line',
        'difference',
        'recommendation',
        'sample_size',
        'edge_strength',
        'final_action',
        'status'
    ]

    return board[columns]

In [313]:
daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,opponent,home_away,games_used,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
2,Zack Wheeler,ATL,Home,24,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,CLE,Home,32,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,BOS,Away,0,NaN,6.5,NaN,No Data,No Data,No Data,Pass,No Data,2025-07-12

In [314]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Add Projection Ingredients to the Board

The projected strikeout number comes from three averages:

- last 3 starts average strikeouts
- last 5 starts average strikeouts
- season average strikeouts

Adding these columns to the board makes the projection easier to understand and review.

In [315]:
def project_pitcher_k(last_name, first_name, season, regular_season_start):
    player_ids = playerid_lookup(last_name, first_name)
    mlbam_id = int(player_ids.iloc[0]['key_mlbam'])

    start_date = regular_season_start
    end_date = f'{season}-10-01'

    data = statcast_pitcher(start_date, end_date, mlbam_id)

    games = (
        data.groupby('game_date')
        .agg(
            strikeouts=('events', lambda x: (x == 'strikeout').sum()),
            pitches=('pitch_type', 'count'),
            avg_velocity=('release_speed', 'mean')
        )
        .reset_index()
        .sort_values('game_date')
    )

    games['last_3_avg_k'] = games['strikeouts'].rolling(3).mean()
    games['last_5_avg_k'] = games['strikeouts'].rolling(5).mean()
    games['season_avg_k'] = games['strikeouts'].expanding().mean()

    latest = games.iloc[-1]

    projected_k = (
        latest['last_3_avg_k'] * 0.4 +
        latest['last_5_avg_k'] * 0.4 +
        latest['season_avg_k'] * 0.2
    )

    return {
        'pitcher': f'{first_name.title()} {last_name.title()}',
        'mlbam_id': mlbam_id,
        'season': season,
        'regular_season_start': regular_season_start,
        'projected_k': projected_k,
        'last_3_avg_k': latest['last_3_avg_k'],
        'last_5_avg_k': latest['last_5_avg_k'],
        'season_avg_k': latest['season_avg_k'],
        'games_used': len(games),
        'games': games
    }

In [316]:
def compare_to_line(result, sportsbook_line):
    projected_k = round(result['projected_k'], 2)
    difference = round(projected_k - sportsbook_line, 2)

    if difference >= 0.5:
        recommendation = 'Over'
    elif difference <= -0.5:
        recommendation = 'Under'
    else:
        recommendation = 'No Bet'

    if result['games_used'] >= 10:
        sample_size = 'Good Sample'
    else:
        sample_size = 'Small Sample'

    summary = pd.DataFrame([{
        'pitcher': result['pitcher'],
        'games_used': result['games_used'],
        'last_3_avg_k': round(result['last_3_avg_k'], 2),
        'last_5_avg_k': round(result['last_5_avg_k'], 2),
        'season_avg_k': round(result['season_avg_k'], 2),
        'projected_k': projected_k,
        'sportsbook_line': sportsbook_line,
        'difference': difference,
        'recommendation': recommendation,
        'sample_size': sample_size
    }])

    return summary

In [317]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            first_name, last_name = split_pitcher_name(pitcher['pitcher'])

            result = project_pitcher_k(
                last_name,
                first_name,
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            summary['opponent'] = pitcher['opponent']
            summary['home_away'] = pitcher['home_away']

            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': pitcher['pitcher'],
                'opponent': pitcher['opponent'],
                'home_away': pitcher['home_away'],
                'games_used': 0,
                'last_3_avg_k': np.nan,
                'last_5_avg_k': np.nan,
                'season_avg_k': np.nan,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    columns = [
        'pitcher',
        'opponent',
        'home_away',
        'games_used',
        'last_3_avg_k',
        'last_5_avg_k',
        'season_avg_k',
        'projected_k',
        'sportsbook_line',
        'difference',
        'recommendation',
        'sample_size',
        'edge_strength',
        'final_action',
        'status'
    ]

    return board[columns]

In [318]:
daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,opponent,home_away,games_used,last_3_avg_k,last_5_avg_k,season_avg_k,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
2,Zack Wheeler,ATL,Home,24,7.67,8.2,8.12,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,CLE,Home,32,10.33,7.8,7.97,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,BOS,Away,0,NaN,NaN,NaN,NaN,6.5,NaN,No Data,No Data,No Data,Pass,No Data,2025-07-12

In [319]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Add Average Pitches Per Start

Strikeout projections depend on opportunity.

One simple way to measure opportunity is average pitches per start.

A pitcher who usually throws more pitches has more chances to record strikeouts, while a pitcher with a lower pitch count may have a lower ceiling.

In [320]:
def project_pitcher_k(last_name, first_name, season, regular_season_start):
    player_ids = playerid_lookup(last_name, first_name)
    mlbam_id = int(player_ids.iloc[0]['key_mlbam'])

    start_date = regular_season_start
    end_date = f'{season}-10-01'

    data = statcast_pitcher(start_date, end_date, mlbam_id)

    games = (
        data.groupby('game_date')
        .agg(
            strikeouts=('events', lambda x: (x == 'strikeout').sum()),
            pitches=('pitch_type', 'count'),
            avg_velocity=('release_speed', 'mean')
        )
        .reset_index()
        .sort_values('game_date')
    )

    games['last_3_avg_k'] = games['strikeouts'].rolling(3).mean()
    games['last_5_avg_k'] = games['strikeouts'].rolling(5).mean()
    games['season_avg_k'] = games['strikeouts'].expanding().mean()
    games['season_avg_pitches'] = games['pitches'].expanding().mean()

    latest = games.iloc[-1]

    projected_k = (
        latest['last_3_avg_k'] * 0.4 +
        latest['last_5_avg_k'] * 0.4 +
        latest['season_avg_k'] * 0.2
    )

    return {
        'pitcher': f'{first_name.title()} {last_name.title()}',
        'mlbam_id': mlbam_id,
        'season': season,
        'regular_season_start': regular_season_start,
        'projected_k': projected_k,
        'last_3_avg_k': latest['last_3_avg_k'],
        'last_5_avg_k': latest['last_5_avg_k'],
        'season_avg_k': latest['season_avg_k'],
        'season_avg_pitches': latest['season_avg_pitches'],
        'games_used': len(games),
        'games': games
    }

In [321]:
def compare_to_line(result, sportsbook_line):
    projected_k = round(result['projected_k'], 2)
    difference = round(projected_k - sportsbook_line, 2)

    if difference >= 0.5:
        recommendation = 'Over'
    elif difference <= -0.5:
        recommendation = 'Under'
    else:
        recommendation = 'No Bet'

    if result['games_used'] >= 10:
        sample_size = 'Good Sample'
    else:
        sample_size = 'Small Sample'

    summary = pd.DataFrame([{
        'pitcher': result['pitcher'],
        'games_used': result['games_used'],
        'last_3_avg_k': round(result['last_3_avg_k'], 2),
        'last_5_avg_k': round(result['last_5_avg_k'], 2),
        'season_avg_k': round(result['season_avg_k'], 2),
        'season_avg_pitches': round(result['season_avg_pitches'], 2),
        'projected_k': projected_k,
        'sportsbook_line': sportsbook_line,
        'difference': difference,
        'recommendation': recommendation,
        'sample_size': sample_size
    }])

    return summary

In [322]:
def build_pitcher_board(pitchers, season, regular_season_start):
    all_summaries = []

    for pitcher in pitchers:
        try:
            first_name, last_name = split_pitcher_name(pitcher['pitcher'])

            result = project_pitcher_k(
                last_name,
                first_name,
                season,
                regular_season_start
            )

            summary = compare_to_line(result, pitcher['line'])
            summary['opponent'] = pitcher['opponent']
            summary['home_away'] = pitcher['home_away']

            all_summaries.append(summary)

        except Exception as e:
            missing_summary = pd.DataFrame([{
                'pitcher': pitcher['pitcher'],
                'opponent': pitcher['opponent'],
                'home_away': pitcher['home_away'],
                'games_used': 0,
                'last_3_avg_k': np.nan,
                'last_5_avg_k': np.nan,
                'season_avg_k': np.nan,
                'season_avg_pitches': np.nan,
                'projected_k': np.nan,
                'sportsbook_line': pitcher['line'],
                'difference': np.nan,
                'recommendation': 'No Data',
                'sample_size': 'No Data',
                'error_message': str(e)
            }])

            all_summaries.append(missing_summary)

    board = pd.concat(all_summaries, ignore_index=True)

    board['edge_strength'] = board['difference'].apply(
        lambda x: 'No Data' if pd.isna(x) else label_edge(x)
    )

    board['final_action'] = board.apply(
        lambda row: 'Pass' if row['recommendation'] == 'No Data' else final_action(row),
        axis=1
    )

    board['status'] = board.apply(add_status, axis=1)

    board['abs_difference'] = board['difference'].abs()
    board = board.sort_values('abs_difference', ascending=False, na_position='last')
    board = board.drop(columns=['abs_difference'])

    columns = [
        'pitcher',
        'opponent',
        'home_away',
        'games_used',
        'last_3_avg_k',
        'last_5_avg_k',
        'season_avg_k',
        'season_avg_pitches',
        'projected_k',
        'sportsbook_line',
        'difference',
        'recommendation',
        'sample_size',
        'edge_strength',
        'final_action',
        'status'
    ]

    return board[columns]

In [323]:
daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,opponent,home_away,games_used,last_3_avg_k,last_5_avg_k,season_avg_k,season_avg_pitches,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
2,Zack Wheeler,ATL,Home,24,7.67,8.2,8.12,99.75,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,CLE,Home,32,10.33,7.8,7.97,92.38,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,BOS,Away,0,NaN,NaN,NaN,NaN,NaN,6.5,NaN,No Data,No Data,No Data,Pass,No Data,2025-07-12

In [324]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Version 1 Summary

This notebook now creates a basic strikeout projection board.

The current version:

1. Uses manually entered sportsbook lines
2. Looks up pitcher IDs with pybaseball
3. Pulls Statcast pitcher data
4. Converts pitch-level data into game-level stats
5. Calculates recent and season strikeout averages
6. Builds a projected strikeout number
7. Compares the projection to the sportsbook line
8. Labels edge strength
9. Returns a final Bet Over, Bet Under, or Pass action

This is a simple first version and should not be treated as a finished betting model yet.

In [325]:
slate_date = '2025-07-12'
season = 2025
regular_season_start = regular_season_start_dates[season]

daily_lines = [
    {'pitcher': 'Tarik Skubal', 'opponent': 'CLE', 'home_away': 'Home', 'line': 7.5},
    {'pitcher': 'Gerrit Cole', 'opponent': 'BOS', 'home_away': 'Away', 'line': 6.5},
    {'pitcher': 'Zack Wheeler', 'opponent': 'ATL', 'home_away': 'Home', 'line': 6.5}
]

daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data
Gathering Player Data

,pitcher,opponent,home_away,games_used,last_3_avg_k,last_5_avg_k,season_avg_k,season_avg_pitches,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
2,Zack Wheeler,ATL,Home,24,7.67,8.2,8.12,99.75,7.97,6.5,1.47,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
0,Tarik Skubal,CLE,Home,32,10.33,7.8,7.97,92.38,8.85,7.5,1.35,Over,Good Sample,Medium Edge,Bet Over,Playable,2025-07-12
1,Gerrit Cole,BOS,Away,0,NaN,NaN,NaN,NaN,NaN,6.5,NaN,No Data,No Data,No Data,Pass,No Data,2025-07-12

In [326]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

## Daily Input Section

This is the section the user updates each day.

To run the board for a new slate, update:

- slate date
- season
- pitcher names
- opponents
- home or away
- sportsbook strikeout lines

The rest of the notebook can stay the same.

In [327]:
slate_date = '2026-06-16'
season = 2026
regular_season_start = regular_season_start_dates[season]

daily_lines = [
    {'pitcher': 'Tarik Skubal', 'opponent': 'CLE', 'home_away': 'Home', 'line': 7.5},
    {'pitcher': 'Zack Wheeler', 'opponent': 'ATL', 'home_away': 'Away', 'line': 6.5}
]

In [328]:
daily_pitcher_board = build_pitcher_board(
    daily_lines,
    season,
    regular_season_start
)

daily_pitcher_board['slate_date'] = slate_date

daily_pitcher_board

Gathering Player Data
Gathering Player Data

,pitcher,opponent,home_away,games_used,last_3_avg_k,last_5_avg_k,season_avg_k,season_avg_pitches,projected_k,sportsbook_line,difference,recommendation,sample_size,edge_strength,final_action,status,slate_date
0,Tarik Skubal,CLE,Home,8,5.33,6.6,6.12,88.25,6.00,7.5,-1.50,Under,Small Sample,Strong Edge,Pass,Pass - Small Sample,2026-06-16
1,Zack Wheeler,ATL,Away,10,7.33,6.4,6.20,94.70,6.73,6.5,0.23,No Bet,Good Sample,No Bet,Pass,Pass - Small Edge,2026-06-16

In [329]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)

In [330]:
daily_pitcher_board = daily_pitcher_board[
    [
        'slate_date',
        'pitcher',
        'opponent',
        'home_away',
        'sportsbook_line',
        'projected_k',
        'difference',
        'final_action',
        'status',
        'recommendation',
        'edge_strength',
        'sample_size',
        'games_used',
        'last_3_avg_k',
        'last_5_avg_k',
        'season_avg_k',
        'season_avg_pitches'
    ]
]

daily_pitcher_board

,slate_date,pitcher,opponent,home_away,sportsbook_line,projected_k,difference,final_action,status,recommendation,edge_strength,sample_size,games_used,last_3_avg_k,last_5_avg_k,season_avg_k,season_avg_pitches
0,2026-06-16,Tarik Skubal,CLE,Home,7.5,6.00,-1.50,Pass,Pass - Small Sample,Under,Strong Edge,Small Sample,8,5.33,6.6,6.12,88.25
1,2026-06-16,Zack Wheeler,ATL,Away,6.5,6.73,0.23,Pass,Pass - Small Edge,No Bet,No Bet,Good Sample,10,7.33,6.4,6.20,94.70

In [331]:
daily_pitcher_board.to_csv(f'../data/daily_pitcher_board_{slate_date}.csv', index=False)